export const CREATE_TASK = 'CREATE_TASK';
export const EDIT_TASK = 'EDIT_TASK';
export const DELETE_TASK = 'DELETE_TASK';
export const TOGGLE_COMPLETE_TASK = 'TOGGLE_COMPLETE_TASK';

export const REQUEST_CREATE_TASK = 'REQUEST_CREATE_TASK';
export const REQUEST_DELETE_TASK = 'REQUEST_DELETE_TASK';
export const REQUEST_EDIT_TASK = 'REQUEST_EDIT_TASK';
export const REQUEST_TOGGLE_COMPLETE_TASK = 'REQUEST_TOGGLE_COMPLETE_TASK';
